repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: pytest
        name: Run all tests using pytest
        entry: pytest
        pass_filenames: false
        language: system
        types: [python]
