version: '3.8'

services:
    bot:
        build: .
        container_name: bot
        depends_on:
            - redis

    redis:
        container_name: bot_redis
        image: "redis:alpine"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
